# Generated by Django 5.0 on 2024-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='post',
            name='insightful',
            field=models.BooleanField(default=False),
        ),
    ]
